# Generated by Django 6.0.6 on 2026-06-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_payment_link_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
